
#include "..\resource.h"

#define IDD_REPLICATOR        1

#define IDS_EDIT_INSTRUCTIONS          1

#define IDDI_REPLICATOR_INSTRUCTIONS         101
#define IDDI_REPLICATOR_RESET                102
#define IDDI_REPLICATOR_ACTION_INSTRUCTIONS  103

#define IDDI_SIGNATURE_REGION_REPLICATE   410
#define IDDI_SIGNATURE_REGION_DELETE      411
#define IDDI_SIGNATURE_REGION_EVERY_PAGE  412

#define IDDI_NO_PROFILE_NOTE  201
