
#define IDDIALOG_PROPERTIES   100

#define IDDI_BATCH_FILE       100
#define IDDI_BATCH_FILE_GET   101

#define IDDI_WAIT_FOR_COMPLETION 102
#define IDDI_TOOLBOX_NEED_ADMIN_PRIVILEGES      1024
