
#define IDDIALOG_PROPERTIES   100

#define IDS_DATABASE_CONNECT_ERROR     1
#define IDS_DATABASE_INSERT_ERROR      2

#define IDDI_GENERAL_DESCRIPTION    101
#define IDDI_DATABASE_LOCATION      102
#define IDDI_DATABASE_LOCATION_GET  103

